export const LOGIN_START    = "LOGIN_START"
export const LOGIN_COMPLETE = "LOGIN_COMPLETE"
export const LOGIN_ERROR    = "LOGIN_ERROR"

export const LOGOUT = "LOGOUT"

export const PROFILE_UPDATE_REQUEST  = "PROFILE_UPDATE_REQUEST"
export const PROFILE_UPDATE_START    = "PROFILE_UPDATE_START"
export const PROFILE_UPDATE_COMPLETE = "PROFILE_UPDATE_COMPLETE"
export const PROFILE_UPDATE_ERROR    = "PROFILE_UPDATE_ERROR"

export const DATATABLE_START    = "DATATABLE_START"
export const DATATABLE_COMPLETE = "DATATABLE_COMPLETE"
export const DATATABLE_ERROR    = "DATATABLE_ERROR"
